version: '3.7'

services:
  keyfi-backend:
    build:
      context: ./keyfi-backend
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
      - '50052:50052'
  gateway-envoy:
    build:
      context: ./config
      dockerfile: Dockerfile-gateway
    ports:
      - '8080:8080'
  keyfi-frontend:
    build:
      context: ./keyfi-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:5173'
  nginx-proxy:
      build:
        context: ./config
        dockerfile: Dockerfile-nginx
      ports:
        - '80:80'   # Expose Nginx HTTP port
  