version: '3.7'

services:
  keyfi-backend:
    build:
      context: ./keyfi-backend
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
      - '8081:50052'
  gateway-envoy:
    build:
      context: ./config
      dockerfile: Dockerfile-gateway
    ports:
      - '8080:8080'
  keyfi-frontend:
    build:
      context: ./keyfi-frontend
      dockerfile: Dockerfile
    ports:
      - '80:5173'
  # No need for now
  # nginx-proxy:
  #     build:
  #       context: ./config
  #       dockerfile: Dockerfile-nginx
  #     ports:
  #       - '8081:8081'   # Expose Nginx HTTP port
  